services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
      - TZ=America/Santiago
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    image: odoo:17.0
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - TZ=America/Santiago
    ports:
      - "8069:8069"
    depends_on:
      - db
    volumes:
      - ./movie_module/:/mnt/extra-addons/movie_module
      - odoo-data:/var/lib/odoo

volumes:
  db-data:
  odoo-data:
